# ***Elevating Diabetic Patient Well-being using Data Processing Frameworks: PySpark***
# ***Date: 14 November 2023***


# **Apache spark is ...**

**1. An open-source computing system,**

**2. A high-performance distributed computing system,**

**3. A fast database framework for processing,**

**4. Process large-scale datasets,**

**5. A cluster computing technology.**




# ***My Information:***

#***My Name: Mohammad Salman***


In [ ]:
!python --version


Python 3.10.12


In [ ]:
!pwd

/content


In [ ]:
!wget https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz

--2023-11-26 08:13:44--  https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz
Resolving dlcdn.apache.org (dlcdn.apache.org)... 151.101.2.132, 2a04:4e42::644
Connecting to dlcdn.apache.org (dlcdn.apache.org)|151.101.2.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 388341449 (370M) [application/x-gzip]
Saving to: ‘spark-3.4.1-bin-hadoop3.tgz’

spark-3.4.1-bin-had 100%[===================>] 370.35M  4.80MB/s    in 5.2s    

2023-11-26 08:13:53 (71.7 MB/s) - ‘spark-3.4.1-bin-hadoop3.tgz’ saved [388341449/388341449]



In [ ]:
!pip install pyspark


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.9/316.9 MB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.0-py2.py3-none-any.whl size=317425345 sha256=005fbccc52b01b5d323347b863ca30b5b15395d3ceb1fc3b2b99f094e5c9a4ba
  Stored in directory: /root/.cache/pip/wheels/41/4e/10/c2cf2467f71c678cfc8a6b9ac9241e5e44a01940da8fbb17fc
Successfully built pyspark


In [ ]:
!pyspark

Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/11/26 08:15:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.5.0
      /_/

Using Python version 3.10.12 (main, Jun 11 2023 05:26:28)
Spark context Web UI available at http://c6b6d2d70c53:4040
Spark context available as 'sc' (master = local[*], app id = local-1700986507128).
SparkSession available as 'spark'.
>>> 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyspark/context.py", line 381, in signal_handler
    self.cancelAllJobs()
  File "/usr/local/lib/python3.10/dist-pa

In [ ]:
!pyspark --version

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.5.0
      /_/
                        
Using Scala version 2.12.18, OpenJDK 64-Bit Server VM, 11.0.21
Branch HEAD
Compiled by user ubuntu on 2023-09-09T01:53:20Z
Revision ce5ddad990373636e94071e7cef2f31021add07b
Url https://github.com/apache/spark
Type --help for more information.


In [ ]:
!tar xvzf spark-3.4.1-bin-hadoop3.tgz

tar (child): spark-3.4.1-bin-hadoop3.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


In [ ]:
!ls /content/spark-3.4.1-bin-hadoop3

ls: cannot access '/content/spark-3.4.1-bin-hadoop3': No such file or directory


In [ ]:
!pip install findspark

In [ ]:
import os
os.environ["Spark_Home"] = "/content/spark-3.4.1-bin-hadoop3"

import findspark
findspark.init

<function findspark.init(spark_home=None, python_path=None, edit_rc=False, edit_profile=False)>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# ***Spark Session***

In [ ]:
from pyspark.sql import SparkSession

In [ ]:
spark = SparkSession.builder.appName("Mohammad Salman").getOrCreate()
print(spark.sparkContext.appName)

Mohammad Salman


# ***Dataset***

In [ ]:
salman = spark.read.csv("/content/drive/MyDrive/FALL 2023 ALL/BIG DATA AND IOT LAB/Project/diabetic_data.csv", header=True, inferSchema=True)

In [ ]:
salman.show()

+------------+-----------+---------------+------+--------+------+-----------------+------------------------+-------------------+----------------+----------+--------------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|           race|gender|     age|weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|   medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_diagn

# ***Rows and Features***

In [ ]:
num_rows = salman.count()
num_columns = len(salman.columns)

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 101766
Number of columns: 50


# ***Schema of my DataFrame***

In [ ]:
salman.printSchema()

root
 |-- encounter_id: integer (nullable = true)
 |-- patient_nbr: integer (nullable = true)
 |-- race: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- age: string (nullable = true)
 |-- weight: string (nullable = true)
 |-- admission_type_id: integer (nullable = true)
 |-- discharge_disposition_id: integer (nullable = true)
 |-- admission_source_id: integer (nullable = true)
 |-- time_in_hospital: integer (nullable = true)
 |-- payer_code: string (nullable = true)
 |-- medical_specialty: string (nullable = true)
 |-- num_lab_procedures: integer (nullable = true)
 |-- num_procedures: integer (nullable = true)
 |-- num_medications: integer (nullable = true)
 |-- number_outpatient: integer (nullable = true)
 |-- number_emergency: integer (nullable = true)
 |-- number_inpatient: integer (nullable = true)
 |-- diag_1: string (nullable = true)
 |-- diag_2: string (nullable = true)
 |-- diag_3: string (nullable = true)
 |-- number_diagnoses: integer (nullable = true)
 |-

# ***Unique values of my target feature "readmitted"***

In [ ]:
unique_values = salman.select("readmitted").distinct().collect()

for row in unique_values:
    print(row['readmitted'])

>30
NO
<30


# ***Data Preprocessing and Feature Engineering Starts***

# ***Handling Missing Values***

In [ ]:
salman.describe().show()


+-------+--------------------+--------------------+------+---------------+--------+--------+-----------------+------------------------+-------------------+------------------+----------+-----------------+------------------+------------------+------------------+-------------------+-------------------+------------------+------------------+------------------+------------------+-----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|summary|        encounter_id|         patient_nbr|  race|         gender|     age|  weight|admission_type_id|discharge_disposition_id|admission_source_id|  time_in_hospital|payer_code|medical_specialty|num_lab_procedures|    num_proce

# ***Counting the missing values in each Feature***

In [ ]:
from pyspark.sql.functions import col, sum


In [ ]:
missing_values_salman = salman.select([sum(col(c).isNull().cast("int")).alias(c) for c in salman.columns])

missing_values_salman.show()

+------------+-----------+----+------+---+------+-----------------+------------------------+-------------------+----------------+----------+-----------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|race|gender|age|weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_diagnoses|max_glu_serum|A1Cresult|metformin

# ***No null values, but i have to find it***

In [ ]:
from pyspark.sql.functions import col

salman = salman.na.replace("?", None).na.replace("None", None).na.replace("N/A", None)

missing_values_salman = salman.select([sum(col(c).isNull().cast("int")).alias(c) for c in salman.columns])
missing_values_salman.show()


+------------+-----------+----+------+---+------+-----------------+------------------------+-------------------+----------------+----------+-----------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|race|gender|age|weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_diagnoses|max_glu_serum|A1Cresult|metformin

In [ ]:
salman.show()

+------------+-----------+---------------+------+--------+------+-----------------+------------------------+-------------------+----------------+----------+--------------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|           race|gender|     age|weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|   medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_diagn

# ***Above is the table of total missing values in each feature.***
# ***Now, I have to handle these missing values.***

# ***Handling Missing values***

In [ ]:
from pyspark.sql.functions import mean


# ***Handling missing values for ''Numerical columns'' by mean***

# ***Calculate the mean of each numeric column***

In [ ]:
from pyspark.sql.functions import mean, col

numeric_cols = [col_name for col_name, data_type in salman.dtypes if data_type == "int" or data_type == "double"]


numeric_means = salman.select([mean(col(col_name)).alias(col_name) for col_name in numeric_cols]).collect()[0]

for col_name in numeric_cols:
    salman = salman.na.fill(numeric_means[col_name], [col_name])


In [ ]:
numeric_cols

['encounter_id',
 'patient_nbr',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'number_diagnoses']

In [ ]:
from pyspark.sql.functions import col

salman = salman.replace("?", None)

missing_values_salman = salman.select([sum(col(c).isNull().cast("int")).alias(c) for c in salman.columns])
missing_values_salman.show()


+------------+-----------+----+------+---+------+-----------------+------------------------+-------------------+----------------+----------+-----------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|race|gender|age|weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_diagnoses|max_glu_serum|A1Cresult|metformin

# ***Handling missing values for of each ''String column'' by Mode***

In [ ]:
from pyspark.sql.functions import col

def calculate_mode(df, col_name):
    mode_row = df.filter(col(col_name).isNotNull()) \
                  .groupBy(col_name).count() \
                  .orderBy('count', ascending=False) \
                  .first()

    return mode_row[0] if mode_row else None

string_cols = ['race', 'weight','payer_code', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult']

string_modes = [calculate_mode(salman, col_name) for col_name in string_cols]

In [ ]:
from pyspark.sql.functions import when
for i, col in enumerate(string_cols):
    mode_value = string_modes[i]
    if mode_value is not None:
        salman = salman.withColumn(col, when(salman[col].isNull(), mode_value).otherwise(salman[col]))

# ***Checking is there are any missing values in the entire dataframe***

In [ ]:
from pyspark.sql.functions import col, sum

missing_values = salman.select([sum(col(c).isNull().cast("int")).alias(c) for c in salman.columns])


missing_values.show()


+------------+-----------+----+------+---+------+-----------------+------------------------+-------------------+----------------+----------+-----------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|race|gender|age|weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_diagnoses|max_glu_serum|A1Cresult|metformin

# ***Missing value handling done***

In [ ]:
salman.show()

+------------+-----------+---------------+------+--------+--------+-----------------+------------------------+-------------------+----------------+----------+--------------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|           race|gender|     age|  weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|   medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_d

In [ ]:
from pyspark.sql.functions import col


missing_values = salman.select([col(c).alias(c) for c in salman.columns]).na.drop()


missing_counts = [(col, salman.where(salman[col].isNull()).count()) for col in salman.columns]
missing_counts = [(col, count) for col, count in missing_counts if count > 0]

if len(missing_counts) == 0:
    print("No missing values in the dataset.")
else:
    print("Missing values exist in the dataset.")
    for col, count in missing_counts:
        print(f"Column '{col}' has {count} missing values.")


No missing values in the dataset.


# ***No missing values in the dataset.***

In [ ]:
salman.show()

+------------+-----------+---------------+------+--------+--------+-----------------+------------------------+-------------------+----------------+----------+--------------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|           race|gender|     age|  weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|   medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_d

# ***Now, handling categorical variables by Label Encoding***

# ***Converting the target categorical feature into numerical format using StringIndexer***

In [ ]:
unique_values = salman.select("readmitted").distinct().collect()

for row in unique_values:
    print(row['readmitted'])

>30
NO
<30


In [ ]:
from pyspark.ml.feature import StringIndexer
from pyspark.ml import Pipeline


indexer = StringIndexer(inputCol='readmitted', outputCol='label')

pipeline = Pipeline(stages=[indexer])

model = pipeline.fit(salman)
salman = model.transform(salman)

salman = salman.drop('readmitted')

salman = salman.withColumnRenamed('label', 'readmitted')

salman.show()

+------------+-----------+---------------+------+--------+--------+-----------------+------------------------+-------------------+----------------+----------+--------------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+
|encounter_id|patient_nbr|           race|gender|     age|  weight|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|payer_code|   medical_specialty|num_lab_procedures|num_procedures|num_medications|number_outpatient|number_emergency|number_inpatient|diag_1|diag_2|diag_3|number_d

In [ ]:
unique_values = salman.select("readmitted").distinct().collect()

for row in unique_values:
    print(row['readmitted'])

0.0
1.0
2.0


# ***Converting the independent categorical feature into numerical format using StringIndexer***

In [ ]:
from pyspark.ml.feature import StringIndexer
from pyspark.ml import Pipeline


categorical_cols = [col_name for col_name, data_type in salman.dtypes if data_type == "string"]

In [ ]:
indexers = [StringIndexer(inputCol=col, outputCol=col + "_index", handleInvalid="keep") for col in categorical_cols]


pipeline = Pipeline(stages=indexers)


salman = pipeline.fit(salman).transform(salman)


In [ ]:
salman.show()

+------------+-----------+---------------+------+--------+--------+-----------------+------------------------+-------------------+----------------+----------+--------------------+------------------+--------------+---------------+-----------------+----------------+----------------+------+------+------+----------------+-------------+---------+---------+-----------+-----------+--------------+-----------+-------------+---------+---------+-----------+------------+-------------+--------+--------+------------+----------+-------+-----------+-------+-------------------+-------------------+------------------------+-----------------------+----------------------+------+-----------+----------+----------+------------+---------+------------+----------------+-----------------------+------------+------------+------------+-------------------+---------------+---------------+-----------------+-----------------+--------------------+-----------------+-------------------+---------------+---------------+-----

In [ ]:
salman = salman.drop(*categorical_cols)


In [ ]:
salman.show()

+------------+-----------+-----------------+------------------------+-------------------+----------------+------------------+--------------+---------------+-----------------+----------------+----------------+----------------+----------+----------+------------+---------+------------+----------------+-----------------------+------------+------------+------------+-------------------+---------------+---------------+-----------------+-----------------+--------------------+-----------------+-------------------+---------------+---------------+-----------------+------------------+-------------------+--------------+--------------+------------------+----------------+-------------+-----------------+-------------+-------------------------+-------------------------+------------------------------+-----------------------------+----------------------------+------------+-----------------+
|encounter_id|patient_nbr|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|num_lab_p

# ***Now, there are no categorical features in the dataframe***

In [ ]:
salman.printSchema()

root
 |-- encounter_id: integer (nullable = true)
 |-- patient_nbr: integer (nullable = true)
 |-- admission_type_id: integer (nullable = true)
 |-- discharge_disposition_id: integer (nullable = true)
 |-- admission_source_id: integer (nullable = true)
 |-- time_in_hospital: integer (nullable = true)
 |-- num_lab_procedures: integer (nullable = true)
 |-- num_procedures: integer (nullable = true)
 |-- num_medications: integer (nullable = true)
 |-- number_outpatient: integer (nullable = true)
 |-- number_emergency: integer (nullable = true)
 |-- number_inpatient: integer (nullable = true)
 |-- number_diagnoses: integer (nullable = true)
 |-- readmitted: double (nullable = false)
 |-- race_index: double (nullable = false)
 |-- gender_index: double (nullable = false)
 |-- age_index: double (nullable = false)
 |-- weight_index: double (nullable = false)
 |-- payer_code_index: double (nullable = false)
 |-- medical_specialty_index: double (nullable = false)
 |-- diag_1_index: double (nulla

In [ ]:
from pyspark.sql.functions import count, when, isnull
salman.select([count(when(isnull(c), c)).alias(c) for c in salman.columns]).show()


+------------+-----------+-----------------+------------------------+-------------------+----------------+------------------+--------------+---------------+-----------------+----------------+----------------+----------------+----------+----------+------------+---------+------------+----------------+-----------------------+------------+------------+------------+-------------------+---------------+---------------+-----------------+-----------------+--------------------+-----------------+-------------------+---------------+---------------+-----------------+------------------+-------------------+--------------+--------------+------------------+----------------+-------------+-----------------+-------------+-------------------------+-------------------------+------------------------------+-----------------------------+----------------------------+------------+-----------------+
|encounter_id|patient_nbr|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|num_lab_p

# ***No null values***

# ***Time for normalization my dataframe to get higher accuracy***

# **Now, Finding Outliers values that may cause of lower accuracy on model Implementation for each feature sequentially from first to last**

# ***Using Z-score***

In [ ]:
from pyspark.sql.functions import *

column_subset = salman.columns

for col in column_subset:
    if salman.select(col).dtypes[0][1] == "string":
        pass
    else:
        col_mean = salman.select(mean(col)).collect()[0][0]
        col_stddev = salman.select(stddev(col)).collect()[0][0]
        upper_limit = col_mean + (3 * col_stddev)
        lower_limit = col_mean - (3 * col_stddev)

        outliers = salman.filter((salman[col] < lower_limit) | (salman[col] > upper_limit))

        if outliers.count() > 0:
            print(f"Outliers in column '{col}':")
            outliers.select(col).show()


Outliers in column 'patient_nbr':
+-----------+
|patient_nbr|
+-----------+
|  186699353|
|  186400166|
|  175297100|
|  174000938|
|  175579403|
|  178345517|
|  173782328|
|  184358588|
|  182647004|
|  183621929|
|  184194626|
|  187143647|
|  183817868|
|  185648369|
|  181891598|
|  174816680|
|  186410174|
|  175070606|
|  180517235|
|  177722195|
+-----------+
only showing top 20 rows

Outliers in column 'admission_type_id':
+-----------------+
|admission_type_id|
+-----------------+
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
|                8|
+-----------------+
only showing top 20 rows

Outliers in column 'discharge_disposition_id':
+----------

# ***Dataframe values after filtering out the outliers using Z-score.***

In [ ]:
from pyspark.sql.functions import *

column_subset = salman.columns

for col in column_subset:
    if salman.select(col).dtypes[0][1] == "string":
        pass
    else:
        col_mean = salman.select(mean(col)).collect()[0][0]
        col_stddev = salman.select(stddev(col)).collect()[0][0]
        upper_limit = col_mean + (3 * col_stddev)
        lower_limit = col_mean - (3 * col_stddev)
        salman = salman.filter((salman[col] >= lower_limit) & (salman[col] <= upper_limit))

salman.show()


+------------+-----------+-----------------+------------------------+-------------------+----------------+------------------+--------------+---------------+-----------------+----------------+----------------+----------------+----------+----------+------------+---------+------------+----------------+-----------------------+------------+------------+------------+-------------------+---------------+---------------+-----------------+-----------------+--------------------+-----------------+-------------------+---------------+---------------+-----------------+------------------+-------------------+--------------+--------------+------------------+----------------+-------------+-----------------+-------------+-------------------------+-------------------------+------------------------------+-----------------------------+----------------------------+------------+-----------------+
|encounter_id|patient_nbr|admission_type_id|discharge_disposition_id|admission_source_id|time_in_hospital|num_lab_p

# ***Dataframe rows and columns after filtering Outliers***

In [ ]:
num_rows = salman.count()
num_columns = len(salman.columns)

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 54952
Number of columns: 50


# ***Feature engineering, scaling and outliers handling done***

# ***Now, applying 5 ML models which can perform best***

# ***01. Random Forest Classification***

In [ ]:
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.feature import VectorAssembler
from pyspark.ml import Pipeline
from pyspark.ml.evaluation import MulticlassClassificationEvaluator


feature_cols = [col_name for col_name in salman.columns if col_name != 'readmitted']

assembler = VectorAssembler(inputCols=feature_cols, outputCol='features')

rf_classifier = RandomForestClassifier(labelCol='readmitted', featuresCol='features', numTrees=100, seed=42, maxBins=800)

pipeline = Pipeline(stages=[assembler, rf_classifier])

train_data, test_data = salman.randomSplit([0.8, 0.2], seed=42)

model = pipeline.fit(train_data)

predictions = model.transform(test_data)

evaluator = MulticlassClassificationEvaluator(labelCol='readmitted', metricName='accuracy',)
accuracy = evaluator.evaluate(predictions)
print(f"Random Forest Model Accuracy: {accuracy}")


Random Forest Model Accuracy: 0.9036907822254866


# ***Yes I got a good accuracy, Model Accuracy: 0.9036***

# ***Confusion Matrix***

In [ ]:
from pyspark.mllib.evaluation import MulticlassMetrics

prediction_and_labels = predictions.select("prediction", "readmitted").rdd

metrics = MulticlassMetrics(prediction_and_labels)

confusion_matrix = metrics.confusionMatrix().toArray()
print("Confusion Matrix:")
print(confusion_matrix)


/usr/local/lib/python3.10/dist-packages/pyspark/sql/context.py:158: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(


Confusion Matrix:
[[5994.    0.    0.]
 [   0. 3754.    0.]
 [   0. 1049.   95.]]


# ***02. LogisticRegression***

In [ ]:
from pyspark.ml.classification import LogisticRegression

lr_classifier = LogisticRegression(labelCol='readmitted', featuresCol='features', maxIter=10)

pipeline_lr = Pipeline(stages=[assembler, lr_classifier])

train_data_lr, test_data_lr = salman.randomSplit([0.8, 0.2], seed=42)

model_lr = pipeline_lr.fit(train_data_lr)

predictions_lr = model_lr.transform(test_data_lr)

evaluator_lr = MulticlassClassificationEvaluator(labelCol='readmitted', metricName='accuracy')
accuracy_lr = evaluator_lr.evaluate(predictions_lr)
print(f"Logistic Regression Model Accuracy: {accuracy_lr}")


Logistic Regression Model Accuracy: 1.0


# ***Model Accuracy: 1.0***

# ***Confusion Matrix***

In [ ]:
prediction_and_labels_lr = predictions_lr.select("prediction", "readmitted").rdd
metrics_lr = MulticlassMetrics(prediction_and_labels_lr)
confusion_matrix_lr = metrics_lr.confusionMatrix().toArray()
print("Confusion Matrix:")
print(confusion_matrix_lr)

/usr/local/lib/python3.10/dist-packages/pyspark/sql/context.py:158: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(


Confusion Matrix:
[[5994.    0.    0.]
 [   0. 3754.    0.]
 [   0.    0. 1144.]]


# ***03. Decision Tree***

In [ ]:
from pyspark.ml.classification import DecisionTreeClassifier

feature_cols = [col_name for col_name in salman.columns if col_name != 'readmitted']
assembler = VectorAssembler(inputCols=feature_cols, outputCol='features')


dt_classifier = DecisionTreeClassifier(labelCol='readmitted', featuresCol='features', maxDepth=5, maxBins=800)

pipeline_dt = Pipeline(stages=[assembler, dt_classifier])

train_data_dt, test_data_dt = salman.randomSplit([0.8, 0.2], seed=42)

model_dt = pipeline_dt.fit(train_data_dt)

predictions_dt = model_dt.transform(test_data_dt)

evaluator_dt = MulticlassClassificationEvaluator(labelCol='readmitted', metricName='accuracy')
accuracy_dt = evaluator_dt.evaluate(predictions_dt)
print(f"Decision Tree Model Accuracy: {accuracy_dt}")


Decision Tree Model Accuracy: 1.0


# ***Confusion Matrix for decision tree***

In [ ]:
prediction_and_labels_dt = predictions_dt.select("prediction", "readmitted").rdd
metrics_dt = MulticlassMetrics(prediction_and_labels_dt)
confusion_matrix_dt = metrics_dt.confusionMatrix().toArray()
print("Confusion Matrix:")
print(confusion_matrix_dt)

Confusion Matrix:
[[5994.    0.    0.]
 [   0. 3754.    0.]
 [   0.    0. 1144.]]


# ***Assalamualaikum***

# ***The End***